version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: crud_renan_fretta
      MYSQL_USER: renanfretta
      MYSQL_PASSWORD: renan123
    ports:
      - "3306:3306"